### PR TITLE
Fixed backwards ternaries in ban, crash, rejoin, 0 arguments no longer valid

### PR DESCRIPTION
**Pull request by TheUbMunster**
fix for #16

### CODE REVIEW

**Comment by piplup55** [comment]
cool i'll test it soon

**Comment by piplup55** [comment]
a few notes "ban *" doesn't work
image

and it seems to not check for exact name
image

**Comment by piplup55** [comment]
"ban *" is now fixed
image

quotes aren't works as they should
image

discord quotes works great
image

**Review by piplup55 — APPROVED** [review]
everything is fixed and this is ready for merge

**Review by Sanae6 — APPROVED** [review]

**Pull request merged**
